### ISSUE TITLE
License files

### ISSUE THREAD

**Issue by schnorr** [VNNikolaidis/nnlib2Rcpp#2]
There are two files with two licenses: `LICENSE` and `LICENSE.md`. The former has a copyright notice pointing to the author, the second contains a MIT license which is an OSI approved one. I suggest to the author:

- [ ] put a link pointing to the https://opensource.org/licenses/MIT text

**Comment by VNNikolaidis** [comment]
Thank you for the comment. The file LICENCE is written as is to be compatible with the CRAN submission rules, while the LICENSE.md is there for GitHub. Of course they both contain the same licensing information, but this has been an known issue (that it is hard to satisfy both in a single file). See for example the discussion in:

https://stackoverflow.com/questions/43550479/how-to-satisfy-both-cran-and-github-license-file-naming-requirements

I will look a little more into this issue although my priority is to comply with CRAN (they are quite strict) while also have the files in the GitHub repository as close as possible to those used when creating the final CRAN submission.

**Comment by VNNikolaidis** [comment]
The format used for LICENSE is the one imposed by CRAN. As far as I am aware, CRAN submission rules imply that only a separate  LICENSE.md can be used.
