### ISSUE TITLE
Typo in the blog post when definining the desired data out matrix

### ISSUE THREAD

**Issue by schnorr** [VNNikolaidis/nnlib2Rcpp#4]
Hi, I was repeating the procedure available at https://r-posts.com/creating-custom-neural-networks-with-nnlib2rcpp/ and I think there is a typo there. Instead of `desired_data_out <- matrix(data=0, nrow=cases, ncol=3)` you may want to have `desired_data_out <- matrix(data=0, nrow=iris_cases, ncol=3)`.

**Comment by VNNikolaidis** [comment]
Dear schnorr, you are right, I really thank you for pointing that out, it was indeed a typo. I corrected the post. It should work now.

**Comment by VNNikolaidis** [comment]
It was a typo in the blog post, now corrected.
